In [9]:
import pandas as pd

In [17]:
import geopandas as gpd

In [11]:
path = "../data/raw/Adresser til brug af skoledistrikter i KK 2026_02_19.xlsx"

In [12]:
xls = pd.ExcelFile(path)
xls.sheet_names

['Ark1']

In [13]:
df = pd.read_excel(path, sheet_name=xls.sheet_names[0])
df.head()

,Koerselsdato,Kommunekode,Kommunenavn,Adresse,Vejkode,Vejnavn,Husnr,Husnummer,Husbogstav,Stednavn,...,Skoledistriktsnr,Skoledistriktsnr_3_cifre,Skoledistriktsnavn,Socialdistriktsnavn,Sognekode,Sognenavn,GIS_koor_X,GIS_koor_Y,Longitude,Latitude
0,2026-02-19,101,København,A-Vej 13,286,A-Vej,13,13,NaN,NaN,...,281053,853,Nordøstamager Skole,Amager,7082,Vor Frelsers,728901.86,6176142.36,12.640786,55.677011
1,2026-02-19,101,København,A.C. Meyers Vænge 1,4734,A.C. Meyers Vænge,1,1,NaN,NaN,...,281060,860,Sluseholmen Skole,Valby-Vesterbro-Kgs. Enghave,9165,Sydhavn,722956.55,6173122.88,12.543978,55.652697
2,2026-02-19,101,København,A.C. Meyers Vænge 2,4734,A.C. Meyers Vænge,2,2,NaN,NaN,...,281060,860,Sluseholmen Skole,Valby-Vesterbro-Kgs. Enghave,9165,Sydhavn,722940.54,6173165.25,12.543759,55.653085
3,2026-02-19,101,København,A.C. Meyers Vænge 3,4734,A.C. Meyers Vænge,3,3,NaN,NaN,...,281060,860,Sluseholmen Skole,Valby-Vesterbro-Kgs. Enghave,9165,Sydhavn,722950.72,6173111.30,12.543876,55.652596
4,2026-02-19,101,København,A.C. Meyers Vænge 4,4734,A.C. Meyers Vænge,4,4,NaN,NaN,...,281060,860,Sluseholmen Skole,Valby-Vesterbro-Kgs. Enghave,9165,Sydhavn,722928.31,6173172.15,12.543570,55.653152

In [14]:
df.columns

Index(['Koerselsdato', 'Kommunekode', 'Kommunenavn', 'Adresse', 'Vejkode',
       'Vejnavn', 'Husnr', 'Husnummer', 'Husbogstav', 'Stednavn', 'Postnr',
       'Postdistrikt', 'Karrenr', 'Rodenr', 'Rodenavn', 'Lokaludvalgsnr',
       'Lokaludvalgsnavn', 'Bydelsnr', 'Bydelsnavn', 'Omraadenavn',
       'Skoledistriktsnr', 'Skoledistriktsnr_3_cifre', 'Skoledistriktsnavn',
       'Socialdistriktsnavn', 'Sognekode', 'Sognenavn', 'GIS_koor_X',
       'GIS_koor_Y', 'Longitude', 'Latitude'],
      dtype='object')

In [15]:
df.shape

(85084, 30)

In [18]:
gdf = gpd.GeoDataFrame(
    df,
    geometry=gpd.points_from_xy(df["Longitude"], df["Latitude"]),
    crs="EPSG:4326"
)

gdf.head()

,Koerselsdato,Kommunekode,Kommunenavn,Adresse,Vejkode,Vejnavn,Husnr,Husnummer,Husbogstav,Stednavn,...,Skoledistriktsnr_3_cifre,Skoledistriktsnavn,Socialdistriktsnavn,Sognekode,Sognenavn,GIS_koor_X,GIS_koor_Y,Longitude,Latitude,geometry
0,2026-02-19,101,København,A-Vej 13,286,A-Vej,13,13,NaN,NaN,...,853,Nordøstamager Skole,Amager,7082,Vor Frelsers,728901.86,6176142.36,12.640786,55.677011,POINT (12.64079 55.67701)
1,2026-02-19,101,København,A.C. Meyers Vænge 1,4734,A.C. Meyers Vænge,1,1,NaN,NaN,...,860,Sluseholmen Skole,Valby-Vesterbro-Kgs. Enghave,9165,Sydhavn,722956.55,6173122.88,12.543978,55.652697,POINT (12.54398 55.65270)
2,2026-02-19,101,København,A.C. Meyers Vænge 2,4734,A.C. Meyers Vænge,2,2,NaN,NaN,...,860,Sluseholmen Skole,Valby-Vesterbro-Kgs. Enghave,9165,Sydhavn,722940.54,6173165.25,12.543759,55.653085,POINT (12.54376 55.65308)
3,2026-02-19,101,København,A.C. Meyers Vænge 3,4734,A.C. Meyers Vænge,3,3,NaN,NaN,...,860,Sluseholmen Skole,Valby-Vesterbro-Kgs. Enghave,9165,Sydhavn,722950.72,6173111.30,12.543876,55.652596,POINT (12.54388 55.65260)
4,2026-02-19,101,København,A.C. Meyers Vænge 4,4734,A.C. Meyers Vænge,4,4,NaN,NaN,...,860,Sluseholmen Skole,Valby-Vesterbro-Kgs. Enghave,9165,Sydhavn,722928.31,6173172.15,12.543570,55.653152,POINT (12.54357 55.65315)

In [20]:
gdf = gdf.to_crs(epsg=25832)  # Denmark has the UTM zone 32